stages:
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - main
  script:
    - add-apt-repository ppa:deadsnakes/ppa &&
    - apt-get update &&
    - apt-get install -y curl python3.11 &&
    - curl -fsSL https://bootstrap.pypa.io/get-pip.py | python3.11 &&
    - pip install -r requirements.txt &&
    - export PYTHONPATH="${PYTHONPATH}:$(pwd)/services" &&
    - curl -fsSL https://railway.app/install.sh | sh &&
    - railway up --service=$RAILWAY_SERVICE_NAME -d
