stages:
  - deploy

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - main
  script:
    - add-apt-repository ppa:deadsnakes/ppa &&
    - apt-get update &&
    - apt-get install -y curl python3.11 &&
    - python -m pip install --upgrade pip && 
    - pip install -r requirements.txt &&
    - pushd ./services && export PYTHONPATH="${PYTHONPATH}:$(pwd)"
    - curl -fsSL https://railway.app/install.sh | sh &&
    - export RAILWAY_TOKEN=$RAILWAY_TOKEN &&
    - railway up --service=$RAILWAY_SERVICE_NAME -d &&
    - railway run uvicorn services.auth.main:app --port 443